package cpufeatures.x86;

import cpufeatures.CpuFeatures;
import io.github.aecsocket.jniglue.JniCallback;
import io.github.aecsocket.jniglue.JniNative;
import io.github.aecsocket.jniglue.JniReferenced;

@JniNative(CpuFeatures.JNI_MODEL)
@JniReferenced
public final class X86Features {
    public final boolean fpu;
    public final boolean tsc;
    public final boolean cx8;
    public final boolean clfsh;
    public final boolean mmx;
    public final boolean aes;
    public final boolean erms;
    public final boolean f16c;
    public final boolean fma4;
    public final boolean fma3;
    public final boolean vaes;
    public final boolean vpclmulqdq;
    public final boolean bmi1;
    public final boolean hle;
    public final boolean bmi2;
    public final boolean rtm;
    public final boolean rdseed;
    public final boolean clflushopt;
    public final boolean clwb;
    public final boolean sse;
    public final boolean sse2;
    public final boolean sse3;
    public final boolean ssse3;
    public final boolean sse4_1;
    public final boolean sse4_2;
    public final boolean sse4a;
    public final boolean avx;
    public final boolean avx_vnni;
    public final boolean avx2;
    public final boolean avx512f;
    public final boolean avx512cd;
    public final boolean avx512er;
    public final boolean avx512pf;
    public final boolean avx512bw;
    public final boolean avx512dq;
    public final boolean avx512vl;
    public final boolean avx512ifma;
    public final boolean avx512vbmi;
    public final boolean avx512vbmi2;
    public final boolean avx512vnni;
    public final boolean avx512bitalg;
    public final boolean avx512vpopcntdq;
    public final boolean avx512_4vnniw;
    public final boolean avx512_4vbmi2;
    public final boolean avx512_second_fma;
    public final boolean avx512_4fmaps;
    public final boolean avx512_bf16;
    public final boolean avx512_vp2intersect;
    public final boolean avx512_fp16;
    public final boolean amx_bf16;
    public final boolean amx_tile;
    public final boolean amx_int8;
    public final boolean pclmulqdq;
    public final boolean smx;
    public final boolean sgx;
    public final boolean cx16;
    public final boolean sha;
    public final boolean popcnt;
    public final boolean movbe;
    public final boolean rdrnd;
    public final boolean dca;
    public final boolean ss;
    public final boolean adx;
    public final boolean lzcnt;
    public final boolean gfni;
    public final boolean movdiri;
    public final boolean movdir64b;
    public final boolean fs_rep_mov;
    public final boolean fz_rep_movsb;
    public final boolean fs_rep_stosb;
    public final boolean fs_rep_cmpsb_scasb;

    @JniCallback
    public X86Features(boolean fpu, boolean tsc, boolean cx8, boolean clfsh, boolean mmx, boolean aes, boolean erms, boolean f16c, boolean fma4, boolean fma3, boolean vaes, boolean vpclmulqdq, boolean bmi1, boolean hle, boolean bmi2, boolean rtm, boolean rdseed, boolean clflushopt, boolean clwb, boolean sse, boolean sse2, boolean sse3, boolean ssse3, boolean sse4_1, boolean sse4_2, boolean sse4a, boolean avx, boolean avx_vnni, boolean avx2, boolean avx512f, boolean avx512cd, boolean avx512er, boolean avx512pf, boolean avx512bw, boolean avx512dq, boolean avx512vl, boolean avx512ifma, boolean avx512vbmi, boolean avx512vbmi2, boolean avx512vnni, boolean avx512bitalg, boolean avx512vpopcntdq, boolean avx512_4vnniw, boolean avx512_4vbmi2, boolean avx512_second_fma, boolean avx512_4fmaps, boolean avx512_bf16, boolean avx512_vp2intersect, boolean avx512_fp16, boolean amx_bf16, boolean amx_tile, boolean amx_int8, boolean pclmulqdq, boolean smx, boolean sgx, boolean cx16, boolean sha, boolean popcnt, boolean movbe, boolean rdrnd, boolean dca, boolean ss, boolean adx, boolean lzcnt, boolean gfni, boolean movdiri, boolean movdir64b, boolean fs_rep_mov, boolean fz_rep_movsb, boolean fs_rep_stosb, boolean fs_rep_cmpsb_scasb) {
        this.fpu = fpu;
        this.tsc = tsc;
        this.cx8 = cx8;
        this.clfsh = clfsh;
        this.mmx = mmx;
        this.aes = aes;
        this.erms = erms;
        this.f16c = f16c;
        this.fma4 = fma4;
        this.fma3 = fma3;
        this.vaes = vaes;
        this.vpclmulqdq = vpclmulqdq;
        this.bmi1 = bmi1;
        this.hle = hle;
        this.bmi2 = bmi2;
        this.rtm = rtm;
        this.rdseed = rdseed;
        this.clflushopt = clflushopt;
        this.clwb = clwb;
        this.sse = sse;
        this.sse2 = sse2;
        this.sse3 = sse3;
        this.ssse3 = ssse3;
        this.sse4_1 = sse4_1;
        this.sse4_2 = sse4_2;
        this.sse4a = sse4a;
        this.avx = avx;
        this.avx_vnni = avx_vnni;
        this.avx2 = avx2;
        this.avx512f = avx512f;
        this.avx512cd = avx512cd;
        this.avx512er = avx512er;
        this.avx512pf = avx512pf;
        this.avx512bw = avx512bw;
        this.avx512dq = avx512dq;
        this.avx512vl = avx512vl;
        this.avx512ifma = avx512ifma;
        this.avx512vbmi = avx512vbmi;
        this.avx512vbmi2 = avx512vbmi2;
        this.avx512vnni = avx512vnni;
        this.avx512bitalg = avx512bitalg;
        this.avx512vpopcntdq = avx512vpopcntdq;
        this.avx512_4vnniw = avx512_4vnniw;
        this.avx512_4vbmi2 = avx512_4vbmi2;
        this.avx512_second_fma = avx512_second_fma;
        this.avx512_4fmaps = avx512_4fmaps;
        this.avx512_bf16 = avx512_bf16;
        this.avx512_vp2intersect = avx512_vp2intersect;
        this.avx512_fp16 = avx512_fp16;
        this.amx_bf16 = amx_bf16;
        this.amx_tile = amx_tile;
        this.amx_int8 = amx_int8;
        this.pclmulqdq = pclmulqdq;
        this.smx = smx;
        this.sgx = sgx;
        this.cx16 = cx16;
        this.sha = sha;
        this.popcnt = popcnt;
        this.movbe = movbe;
        this.rdrnd = rdrnd;
        this.dca = dca;
        this.ss = ss;
        this.adx = adx;
        this.lzcnt = lzcnt;
        this.gfni = gfni;
        this.movdiri = movdiri;
        this.movdir64b = movdir64b;
        this.fs_rep_mov = fs_rep_mov;
        this.fz_rep_movsb = fz_rep_movsb;
        this.fs_rep_stosb = fs_rep_stosb;
        this.fs_rep_cmpsb_scasb = fs_rep_cmpsb_scasb;
    }
}
