package cpufeatures.x86;

import java.util.function.Predicate;

public enum X86Feature {
    FPU                 ((x) -> x.fpu),
    TSC                 ((x) -> x.tsc),
    CX8                 ((x) -> x.cx8),
    CLFSH               ((x) -> x.clfsh),
    MMX                 ((x) -> x.mmx),
    AES                 ((x) -> x.aes),
    ERMS                ((x) -> x.erms),
    F16C                ((x) -> x.f16c),
    FMA4                ((x) -> x.fma4),
    FMA3                ((x) -> x.fma3),
    VAES                ((x) -> x.vaes),
    VPCLMULQDQ          ((x) -> x.vpclmulqdq),
    BMI1                ((x) -> x.bmi1),
    HLE                 ((x) -> x.hle),
    BMI2                ((x) -> x.bmi2),
    RTM                 ((x) -> x.rtm),
    RDSEED              ((x) -> x.rdseed),
    CLFLUSHOPT          ((x) -> x.clflushopt),
    CLWB                ((x) -> x.clwb),
    SSE                 ((x) -> x.sse),
    SSE2                ((x) -> x.sse2),
    SSE3                ((x) -> x.sse3),
    SSSE3               ((x) -> x.ssse3),
    SSE4_1              ((x) -> x.sse4_1),
    SSE4_2              ((x) -> x.sse4_2),
    SSE4A               ((x) -> x.sse4a),
    AVX                 ((x) -> x.avx),
    AVX_VNNI            ((x) -> x.avx_vnni),
    AVX2                ((x) -> x.avx2),
    AVX512F             ((x) -> x.avx512f),
    AVX512CD            ((x) -> x.avx512cd),
    AVX512ER            ((x) -> x.avx512er),
    AVX512PF            ((x) -> x.avx512pf),
    AVX512BW            ((x) -> x.avx512bw),
    AVX512DQ            ((x) -> x.avx512dq),
    AVX512VL            ((x) -> x.avx512vl),
    AVX512IFMA          ((x) -> x.avx512ifma),
    AVX512VBMI          ((x) -> x.avx512vbmi),
    AVX512VBMI2         ((x) -> x.avx512vbmi2),
    AVX512VNNI          ((x) -> x.avx512vnni),
    AVX512BITALG        ((x) -> x.avx512bitalg),
    AVX512VPOPCNTDQ     ((x) -> x.avx512vpopcntdq),
    AVX512_4VNNIW       ((x) -> x.avx512_4vnniw),
    AVX512_4VBMI2       ((x) -> x.avx512_4vbmi2),
    AVX512_SECOND_FMA   ((x) -> x.avx512_second_fma),
    AVX512_4FMAPS       ((x) -> x.avx512_4fmaps),
    AVX512_BF16         ((x) -> x.avx512_bf16),
    AVX512_VP2INTERSECT ((x) -> x.avx512_vp2intersect),
    AVX512_FP16         ((x) -> x.avx512_fp16),
    AMX_BF16            ((x) -> x.amx_bf16),
    AMX_TILE            ((x) -> x.amx_tile),
    AMX_INT8            ((x) -> x.amx_int8),
    PCLMULQDQ           ((x) -> x.pclmulqdq),
    SMX                 ((x) -> x.smx),
    SGX                 ((x) -> x.sgx),
    CX16                ((x) -> x.cx16),
    SHA                 ((x) -> x.sha),
    POPCNT              ((x) -> x.popcnt),
    MOVBE               ((x) -> x.movbe),
    RDRND               ((x) -> x.rdrnd),
    DCA                 ((x) -> x.dca),
    SS                  ((x) -> x.ss),
    ADX                 ((x) -> x.adx),
    LZCNT               ((x) -> x.lzcnt),
    GFNI                ((x) -> x.gfni),
    MOVDIRI             ((x) -> x.movdiri),
    MOVDIR64B           ((x) -> x.movdir64b),
    FS_REP_MOV          ((x) -> x.fs_rep_mov),
    FZ_REP_MOVSB        ((x) -> x.fz_rep_movsb),
    FS_REP_STOSB        ((x) -> x.fs_rep_stosb),
    FS_REP_CMPSB_SCASB  ((x) -> x.fs_rep_cmpsb_scasb);

    private final Predicate<X86Features> has;

    X86Feature(Predicate<X86Features> has) {
        this.has = has;
    }

    public boolean has(X86Features features) { return has.test(features); }
}
