// Generated by jextract

package cpufeatures.headers.x86;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

class constants$1 {

    static final FunctionDescriptor GetX86MicroarchitectureName$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GetX86MicroarchitectureName$MH = RuntimeHelper.downcallHandle(
        "GetX86MicroarchitectureName",
        constants$1.GetX86MicroarchitectureName$FUNC
    );
    static final MemorySegment CPU_FEATURES_VENDOR_GENUINE_INTEL$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("GenuineIntel");
    static final MemorySegment CPU_FEATURES_VENDOR_AUTHENTIC_AMD$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("AuthenticAMD");
    static final MemorySegment CPU_FEATURES_VENDOR_HYGON_GENUINE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("HygonGenuine");
    static final MemorySegment CPU_FEATURES_VENDOR_CENTAUR_HAULS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("CentaurHauls");
    static final MemorySegment CPU_FEATURES_VENDOR_SHANGHAI$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("  Shanghai  ");
}


