// Generated by jextract

package cpufeatures.headers.x86;

import java.lang.foreign.*;

public class X86Features {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        // cpu-features-java
        Constants$root.C_INT$LAYOUT.withName("a"),
        Constants$root.C_INT$LAYOUT.withName("b"),
        Constants$root.C_INT$LAYOUT.withName("c")
    );
    public static MemoryLayout $LAYOUT() {
        return X86Features.$struct$LAYOUT;
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


