import io.github.krakowski.jextract.JextractTask

/* when using jextract:
 * 1. `apply false` -> `apply true`
 * 2. `gradle jextract`
 * 3. copy the autogenerated code from `build/generated/sources/jextract` to `src/main/java`
 * 4. `apply true` -> `apply false`
 * 5. `gradle clean`
 */

plugins {
    id("java-conventions")
    id("jextract-conventions") apply false
}

publishIfNeeded()

tasks {
    withType<JextractTask> {
        // uncomment the block specific to your machine's architecture

//        header("$cpuFeaturesDir/include/cpuinfo_aarch64.h") {
//            targetPackage.set("cpufeatures.headers.aarch64")
//            className.set("CpuInfoAarch64")
//        }

        header("$cpuFeaturesDir/include/cpuinfo_x86.h") {
            targetPackage.set("cpufeatures.headers.x86")
            className.set("CpuInfoX86")
        }
    }
}
