import io.github.krakowski.jextract.JextractTask

/* when using jextract:
 * 1. `apply false` -> `apply true`
 * 2. uncomment the header blocks
 * 3. `gradle jextract`
 * 4. copy the autogenerated code from `build/generated/sources/jextract` to `src/main/java`
 * 6. recomment header blocks
 * 7. `apply true` -> `apply false`
 */

plugins {
    id("java-conventions")
    id("jextract-conventions") apply false
}

tasks {
    withType<JextractTask> {
//        header("$cpuFeaturesDir/include/cpuinfo_aarch64.h") {
//            targetPackage.set("cpufeatures.headers.aarch64")
//            className.set("CpuInfoAarch64")
//        }

//        header("$cpuFeaturesDir/include/cpuinfo_x86.h") {
//            targetPackage.set("cpufeatures.headers.x86")
//            className.set("CpuInfoX86")
//        }
    }
}
