// Generated by jextract

package cpufeatures.natives;

import static java.lang.foreign.ValueLayout.*;
public class Constants$root {

    static final  OfBoolean C_BOOL$LAYOUT = ValueLayout.JAVA_BOOLEAN;
    static final  OfByte C_CHAR$LAYOUT = ValueLayout.JAVA_BYTE;
    static final  OfShort C_SHORT$LAYOUT = ValueLayout.JAVA_SHORT.withBitAlignment(16);
    static final  OfInt C_INT$LAYOUT = ValueLayout.JAVA_INT.withBitAlignment(32);
    static final  OfLong C_LONG$LAYOUT = ValueLayout.JAVA_LONG.withBitAlignment(64);
    static final  OfLong C_LONG_LONG$LAYOUT = ValueLayout.JAVA_LONG.withBitAlignment(64);
    static final  OfFloat C_FLOAT$LAYOUT = ValueLayout.JAVA_FLOAT.withBitAlignment(32);
    static final  OfDouble C_DOUBLE$LAYOUT = ValueLayout.JAVA_DOUBLE.withBitAlignment(64);
    static final  OfAddress C_POINTER$LAYOUT = ValueLayout.ADDRESS.withBitAlignment(64);
}


